In [2]:
import numpy as np
import torch

In [3]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]],dtype='float32')

In [4]:
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [5]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
inputs,targets

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.]]))

In [6]:
w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2,requires_grad=True)
w,b

(tensor([[ 0.9862,  0.4953,  0.6018],
         [ 0.1656, -0.7588,  0.2720]], requires_grad=True),
 tensor([-1.0714, -0.7786], requires_grad=True))

In [7]:
def model(x):
    return x@w.t()+b

In [8]:
preds = model(inputs)
preds,targets

(tensor([[129.9805, -27.8386],
         [170.7705, -35.0820],
         [185.9969, -72.2822],
         [143.0825,  -6.4579],
         [156.6476, -43.1627]], grad_fn=<AddBackward0>),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.]]))

In [9]:
def mse(t1,t2):
    diff = t1-t2
    return (torch.sum(diff*diff))/diff.numel()

In [10]:
loss = mse(preds,targets)
l = torch.sqrt(loss)
loss,l

(tensor(13397.6299, grad_fn=<DivBackward0>),
 tensor(115.7481, grad_fn=<SqrtBackward0>))

In [11]:
loss.backward()

In [12]:
w,w.grad

(tensor([[ 0.9862,  0.4953,  0.6018],
         [ 0.1656, -0.7588,  0.2720]], requires_grad=True),
 tensor([[  7090.1055,   6438.1616,   4209.5361],
         [-10601.4336, -12694.9043,  -7556.4014]]))

In [13]:
b,b.grad

(tensor([-1.0714, -0.7786], requires_grad=True),
 tensor([  81.0956, -128.9647]))

In [14]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

In [15]:
w.grad

tensor([[  7090.1055,   6438.1616,   4209.5361],
        [-10601.4336, -12694.9043,  -7556.4014]])

In [16]:
loss = mse(preds,targets)
loss

tensor(13397.6299, grad_fn=<DivBackward0>)

In [17]:
w.grad.zero_()
b.grad.zero_()
w.grad,b.grad

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([0., 0.]))

In [18]:
preds = model(inputs)
preds,targets

(tensor([[118.6803,  -8.3435],
         [155.9580,  -9.4258],
         [168.7591, -41.6637],
         [131.5238,  12.6115],
         [142.6273, -18.3698]], grad_fn=<AddBackward0>),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.]]))

In [19]:
loss = mse(preds,targets)
loss

tensor(9389.3516, grad_fn=<DivBackward0>)

In [20]:
loss.backward()
w.grad,b.grad

(tensor([[  5926.3184,   5195.4692,   3440.9768],
         [ -8585.9424, -10521.5264,  -6216.9561]]),
 tensor([  67.3097, -105.0383]))

In [21]:
with torch.no_grad():
    w -= w.grad* 1e-5
    b -= b.grad* 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [22]:
w,b

(tensor([[ 0.8560,  0.3789,  0.5253],
         [ 0.3574, -0.5267,  0.4097]], requires_grad=True),
 tensor([-1.0728, -0.7763], requires_grad=True))

In [23]:
preds = model(inputs)
preds,targets

(tensor([[109.3928,   7.6480],
         [143.7902,  11.6263],
         [154.6448, -16.4883],
         [121.9711,  28.1948],
         [131.1412,   2.0081]], grad_fn=<AddBackward0>),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.]]))

In [24]:
loss = mse(preds,targets)
loss

tensor(6683.6904, grad_fn=<DivBackward0>)

In [27]:
for i in range(100000):
    preds = model(inputs)
    loss = mse(preds,targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [28]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(0.4927, grad_fn=<DivBackward0>)


In [29]:
preds, targets

(tensor([[ 56.9840,  70.1767],
         [ 82.3205, 100.7532],
         [118.7227, 132.9801],
         [ 21.1044,  37.0318],
         [101.8912, 119.1167]], grad_fn=<AddBackward0>),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.]]))

Now using built in functions


In [30]:
import torch.nn as nn

In [31]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [32]:
inputs,targets

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.],
         [ 74.,  66.,  43.],
         [ 91.,  87.,  65.],
         [ 88., 134.,  59.],
         [101.,  44.,  37.],
         [ 68.,  96.,  71.],
         [ 73.,  66.,  44.],
         [ 92.,  87.,  64.],
         [ 87., 135.,  57.],
         [103.,  43.,  36.],
         [ 68.,  97.,  70.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 57.,  69.],
         [ 80., 102.],
         [118., 132.],
         [ 21.,  38.],
         [104., 118.],
         [ 57.,  69.],
         [ 82., 100.],
         [118., 134.],
         [ 20.,  38.],
         [102., 120.]]))

In [33]:
from torch.utils.data import TensorDataset

In [34]:
train_ds = TensorDataset(inputs,targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [39]:
from torch.utils.data import DataLoader


In [40]:
bs = 5
train_dl=DataLoader(train_ds,bs,shuffle=True)


In [41]:
for xb,yb in train_dl:
    print(xb,yb)
    break

tensor([[ 68.,  96.,  71.],
        [ 74.,  66.,  43.],
        [ 87., 135.,  57.],
        [101.,  44.,  37.],
        [ 73.,  66.,  44.]]) tensor([[104., 118.],
        [ 57.,  69.],
        [118., 134.],
        [ 21.,  38.],
        [ 57.,  69.]])


In [42]:
model = nn.Linear(3,2)
print(model.weight,model.bias)

Parameter containing:
tensor([[ 0.1611,  0.0576, -0.3304],
        [ 0.5219,  0.4459, -0.0694]], requires_grad=True) Parameter containing:
tensor([-0.2304,  0.3230], requires_grad=True)


In [43]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.1611,  0.0576, -0.3304],
         [ 0.5219,  0.4459, -0.0694]], requires_grad=True),
 Parameter containing:
 tensor([-0.2304,  0.3230], requires_grad=True)]

In [44]:
preds = model(inputs)
preds,targets

(tensor([[  1.1853,  65.3137],
         [ -1.6425,  82.6146],
         [  2.3454, 101.4529],
         [  6.4574,  70.1655],
         [ -6.7086,  74.2826],
         [  1.2888,  65.3898],
         [ -2.0305,  82.0993],
         [  2.1761, 101.9054],
         [  6.3539,  70.0894],
         [ -7.2001,  73.6913],
         [  0.7973,  64.7984],
         [ -1.5390,  82.6907],
         [  2.7334, 101.9681],
         [  6.9489,  70.7568],
         [ -6.8121,  74.2065]], grad_fn=<AddmmBackward0>),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 57.,  69.],
         [ 80., 102.],
         [118., 132.],
         [ 21.,  38.],
         [104., 118.],
         [ 57.,  69.],
         [ 82., 100.],
         [118., 134.],
         [ 20.,  38.],
         [102., 120.]]))

In [45]:
import torch.nn.functional as F

In [46]:
loss_fn = F.mse_loss

In [47]:
loss = loss_fn(preds,targets)
loss

tensor(4008.6128, grad_fn=<MseLossBackward0>)

In [53]:
opt = torch.optim.SGD(model.parameters(),lr=1e-10)

In [54]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
    for epoch in range(num_epochs):
        for xb,yb in train_dl:
            pred = model(xb)
            loss = loss_fn(pred,yb)
            loss.backward()
            opt.step()
            opt.zero_grad()
            
        if (epoch+1)%10 ==0:
             print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [55]:
fit(100,model,loss_fn,opt,train_dl)

Epoch [10/100], Loss: 1.1520
Epoch [20/100], Loss: 0.8055
Epoch [30/100], Loss: 0.6948
Epoch [40/100], Loss: 1.0334
Epoch [50/100], Loss: 0.9246
Epoch [60/100], Loss: 0.8367
Epoch [70/100], Loss: 1.2355
Epoch [80/100], Loss: 0.9778
Epoch [90/100], Loss: 0.9297
Epoch [100/100], Loss: 1.0282


In [59]:
fit(10000,model,loss_fn,opt,train_dl)

Epoch [10/10000], Loss: 1.3296
Epoch [20/10000], Loss: 1.5479
Epoch [30/10000], Loss: 0.8673
Epoch [40/10000], Loss: 0.9240
Epoch [50/10000], Loss: 0.9201
Epoch [60/10000], Loss: 0.8628
Epoch [70/10000], Loss: 1.4985
Epoch [80/10000], Loss: 1.1915
Epoch [90/10000], Loss: 0.9621
Epoch [100/10000], Loss: 0.9337
Epoch [110/10000], Loss: 1.2354
Epoch [120/10000], Loss: 0.8052
Epoch [130/10000], Loss: 0.9724
Epoch [140/10000], Loss: 1.0729
Epoch [150/10000], Loss: 1.3827
Epoch [160/10000], Loss: 1.0105
Epoch [170/10000], Loss: 1.2341
Epoch [180/10000], Loss: 1.0196
Epoch [190/10000], Loss: 1.4795
Epoch [200/10000], Loss: 0.8822
Epoch [210/10000], Loss: 1.4558
Epoch [220/10000], Loss: 0.6628
Epoch [230/10000], Loss: 0.7857
Epoch [240/10000], Loss: 0.8246
Epoch [250/10000], Loss: 0.8884
Epoch [260/10000], Loss: 1.0683
Epoch [270/10000], Loss: 0.9470
Epoch [280/10000], Loss: 0.7415
Epoch [290/10000], Loss: 1.1276
Epoch [300/10000], Loss: 0.6806
Epoch [310/10000], Loss: 1.0661
Epoch [320/10000]

In [60]:
preds,targets

(tensor([[  1.1853,  65.3137],
         [ -1.6425,  82.6146],
         [  2.3454, 101.4529],
         [  6.4574,  70.1655],
         [ -6.7086,  74.2826],
         [  1.2888,  65.3898],
         [ -2.0305,  82.0993],
         [  2.1761, 101.9054],
         [  6.3539,  70.0894],
         [ -7.2001,  73.6913],
         [  0.7973,  64.7984],
         [ -1.5390,  82.6907],
         [  2.7334, 101.9681],
         [  6.9489,  70.7568],
         [ -6.8121,  74.2065]], grad_fn=<AddmmBackward0>),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 57.,  69.],
         [ 80., 102.],
         [118., 132.],
         [ 21.,  38.],
         [104., 118.],
         [ 57.,  69.],
         [ 82., 100.],
         [118., 134.],
         [ 20.,  38.],
         [102., 120.]]))